site_name:  Guardrails AI
site_url: https://getguardrails.ai
site_author: Shreya Rajpal
repo_url: https://github.com/ShreyaR/guardrails
repo_name: ShreyaR/guardrails

remote_branch: gh-pages
remote_name: origin

copyright: |
  Maintained by <a href="https://github.com/shreyar">Shreya Rajpal</a>.


nav:
    - 'Home': index.md
    - 'Getting Started': getting_started.ipynb
    - 'FAQ': faq.md
    - 'RAIL Specification':
      - 'Overview': rail/index.md
      - 'Output Element': rail/output.md
      - 'Prompt Element': rail/prompt.md
      - 'Instruction Element': rail/instructions.md
      - '(Experimental) Script Element': rail/script.md
    - 'Guardrails Reference':
      - 'Guard': guard.md
      - 'Data Types': data_types.md
      - 'Validators': validation.md
      - 'LLM API Wrappers': llm_api_wrappers.md
      - 'Inspecting logs': logs.md
      - 'Guardrails CLI': cli.md
    - 'Applications':
      - 'Text to SQL': use_cases/text2sql/text2sql.ipynb
    - 'Examples':
      - 'Use Guardrails with Chat Models': examples/guardrails_with_chat_models.ipynb
      - 'If condition: generate different JSON objects based on condition': examples/select_choice_based_on_action.ipynb
      - 'Extracting entities from ToS': examples/extracting_entities.ipynb
      - 'Generating bug-free Python code': examples/bug_free_python_code.ipynb
      - 'No secrets in generated text': examples/no_secrets_in_generated_text.ipynb
      - 'Natural language to bug-free SQL': examples/syntax_error_free_sql.ipynb
      - 'Vegan Mac & Cheese Recipe Generator': examples/recipe_generation.ipynb
      - 'Using GPT to play valid chess moves': examples/valid_chess_moves.ipynb
      - 'Translate text with profanity filtering': examples/translation_to_specific_language.ipynb
      - 'Generate structured synthetic data': examples/generate_structured_data.ipynb
      - 'Ensure translated text is high quality': examples/translation_with_quality_check.ipynb
      - 'Check key info present in generated summary': examples/text_summarization_quality.ipynb
    - 'Integrations':
      - 'OpenAI Functions': integrations/openai_functions.ipynb
      - 'LangChain': integrations/langchain.ipynb
      - 'Pydantic': integrations/pydantic_validation.ipynb
    -  'Join the Guardrails AI team': https://equatorial-bergamot-e37.notion.site/Join-the-Guardrails-AI-team-fd2fbf54f7834ba1b4c4d985162d34e1?pvs=4


theme:
  name: material
  favicon: img/favicon.ico
  logo: img/tracks_white.png
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - content.code.annotate
    - toc.follow
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - social
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_bases: false
            show_if_no_docstring: true
            merge_init_into_class: true
            show_root_toc_entry: false
            show_inheritance: true
            show_private: false
            show_special_members: false
  - mknotebooks:
      execute: false
      timeout: 100
      allow_errors: false
      tag_remove_configs:
        remove_cell_tags:
          - Remove_cell
        remove_all_outputs_tags:
          - Remove_all_output
        remove_single_output_tags:
          - Remove_single_output
        remove_input_tags:
          - Remove_input
  # - mkdocs-jupyter:
  #     execute_notebooks: true
  #     kernel_name: python3
  #     extra_arguments:
  #       - "--InlineBackend.figure_format=svg"
  #     include_source: True


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/guardrails_ai
    - icon: fontawesome/brands/github
      link: https://github.com/ShreyaR/guardrails
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Jsey3mX98B
